# Generated by Django 3.2.4 on 2021-07-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0003_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateField(help_text='Fecha de fin', verbose_name='fechafin')),
                ('fechaFinReplanificada', models.DateField(help_text='Fecha de fin replanificada', verbose_name='fechaFinReplanificada')),
                ('fechaInicio', models.DateField(help_text='Fecha de inicio', verbose_name='fechaInicio')),
                ('fechaInicioReplanificada', models.DateField(help_text='Fecha de inicio replanificada', verbose_name='fechaInicioReplanificada')),
                ('horaApertura', models.TimeField(help_text='Hora de apertura', verbose_name='horaApertura')),
                ('horaCierre', models.TimeField(help_text='Hora de cierre', verbose_name='horaCierre')),
                ('nombre', models.TextField(help_text='Nombre de exposición', max_length=200, verbose_name='nombre')),
                ('empleado', models.ForeignKey(help_text='Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Empleado', to='VentaEntradas.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
