# Generated by Django 3.2.4 on 2021-07-03 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0004_exposicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantMaxVisitantes', models.IntegerField(help_text='Cantidad máxima de Vistantes', verbose_name='cantMaxiVistantes')),
                ('cantMaxPorGuia', models.IntegerField(help_text='Cantidad máxima de Vistantes por guía', verbose_name='cantMaxPorGuia')),
                ('nombre', models.TextField(help_text='Nombre de la sede', max_length=200, verbose_name='nombre')),
                ('exposicion', models.ForeignKey(help_text='Exposición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exposición', to='VentaEntradas.exposicion', verbose_name='Exposición')),
            ],
        ),
    ]
