# Generated by Django 3.2.4 on 2021-07-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0005_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioVigencia', models.DateField(help_text='Fecha de incio de vigencia', verbose_name='FechaIncioVigencia')),
                ('fechaFinVigencia', models.DateField(help_text='Fecha de fin de vigencia', verbose_name='fechaFinVigencia')),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto de la tarifa', max_digits=15, verbose_name='monto')),
                ('montoAdicionalGuia', models.DecimalField(decimal_places=2, default=0, help_text='Monto adicional con guía', max_digits=15, verbose_name='montoAdicionalGuia')),
                ('tipoDeEntrada', models.ForeignKey(help_text='Tipo de entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDeEntrada', to='VentaEntradas.tipodeentrada', verbose_name='Tipo de entrada')),
                ('tipoDeVisita', models.ForeignKey(help_text='Tipo de visita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDeVisita', to='VentaEntradas.tipodevisita', verbose_name='Tipo de visita')),
            ],
        ),
    ]
