# Generated by Django 3.2.4 on 2021-07-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0006_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateField(help_text='Fecha de venta', verbose_name='fechaVenta')),
                ('horaVenta', models.TimeField(help_text='Hora de venta', verbose_name='horaVenta')),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto de la entrada', max_digits=15, verbose_name='monto')),
                ('numero', models.IntegerField(help_text='Numero de entrada', verbose_name='numero')),
                ('empleado', models.ForeignKey(help_text='Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to='VentaEntradas.empleado', verbose_name='Empleado')),
                ('sede', models.ForeignKey(help_text='Sede', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sede', to='VentaEntradas.sede', verbose_name='Sede')),
                ('tarifa', models.ForeignKey(help_text='Tarifa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifa', to='VentaEntradas.tarifa', verbose_name='Tarifa')),
            ],
        ),
    ]
