# Generated by Django 3.2.4 on 2021-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0007_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la obra', max_length=200, verbose_name='nombre')),
                ('peso', models.IntegerField(help_text='Peso en kg', verbose_name='peso')),
                ('valuacion', models.DecimalField(decimal_places=2, default=0, help_text='Valuación en pesos', max_digits=10, verbose_name='valuación')),
                ('alto', models.IntegerField(help_text='Alto de la obra', verbose_name='alto')),
                ('ancho', models.IntegerField(help_text='Ancho de la obra', verbose_name='ancho')),
                ('descripcion', models.TextField(help_text='Descripción de la obra', verbose_name='descripción')),
                ('fechaCreacion', models.DateField(help_text='Fecha de creación de la obra', verbose_name='FechaCreacion')),
                ('fechaPrimerIngreso', models.DateField(help_text='Fecha de primer ingreso de la obra', verbose_name='FechaPrimerIngreso')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
