# Generated by Django 3.2.4 on 2021-07-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0009_reservavisita'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorVentaEntradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.ForeignKey(help_text='Entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Entrada', to='VentaEntradas.entrada', verbose_name='Entrada')),
            ],
        ),
    ]
