# Generated by Django 3.2.4 on 2021-08-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0010_gestorventaentradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(help_text='fecha de inicio de sesión', verbose_name='fechaInicio')),
                ('fechaFin', models.DateField(help_text='fecha de fin de sesion', null=True, verbose_name='fechaFin')),
                ('horaInicio', models.TimeField(help_text='hora de inicio de sesion', verbose_name='horaInicio')),
                ('horaFin', models.TimeField(help_text='hora de fin de sesion', verbose_name='horaFin')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(help_text='nombre de usuario', max_length=10, verbose_name='nombre')),
                ('contraseña', models.CharField(help_text='contraseña de usuario', max_length=10, verbose_name='contraseña')),
            ],
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={},
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='fechaVenta',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='horaVenta',
        ),
        migrations.RemoveField(
            model_name='reservavisita',
            name='horaFinReal',
        ),
        migrations.RemoveField(
            model_name='reservavisita',
            name='horaInicioReal',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='montoAdicionalGuia',
        ),
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(help_text='Sede', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd', to='VentaEntradas.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fechaYHoraVenta',
            field=models.DateTimeField(help_text='Fecha de venta', null=True, verbose_name='fechaYHoraVenta'),
        ),
        migrations.AddField(
            model_name='obra',
            name='duracionExtendida',
            field=models.DurationField(help_text='Duración extendida', null=True, verbose_name='DuracionExtendida'),
        ),
        migrations.AddField(
            model_name='obra',
            name='duracionResumida',
            field=models.DurationField(help_text='Duración resumida', null=True, verbose_name='DuracionResumida'),
        ),
        migrations.AddField(
            model_name='reservavisita',
            name='fechaYHoraFinReal',
            field=models.DateTimeField(help_text='Hora de fin real', null=True, verbose_name='horaFinReal'),
        ),
        migrations.AddField(
            model_name='reservavisita',
            name='fechaYHoraInicioReal',
            field=models.DateTimeField(help_text='Hora de inicio real', null=True, verbose_name='horaInicioReal'),
        ),
        migrations.AddField(
            model_name='sede',
            name='diaFin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='diaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='horaApetura',
            field=models.TimeField(null=True, verbose_name='horaApetura'),
        ),
        migrations.AddField(
            model_name='sede',
            name='horaCierre',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='tarifa',
            field=models.ManyToManyField(to='VentaEntradas.Tarifa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cuit',
            field=models.IntegerField(help_text='CUIT', unique=True, verbose_name='cuit'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='empleado',
            field=models.OneToOneField(help_text='Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e', to='VentaEntradas.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='fechaFin',
            field=models.DateField(blank=True, help_text='Fecha de fin', verbose_name='fechafin'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='fechaFinReplanificada',
            field=models.DateField(blank=True, help_text='Fecha de fin replanificada', verbose_name='fechaFinReplanificada'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='horaApertura',
            field=models.TimeField(help_text='Hora de apertura', null=True, verbose_name='horaApertura'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='horaCierre',
            field=models.TimeField(help_text='Hora de cierre', null=True, verbose_name='horaCierre'),
        ),
        migrations.AlterField(
            model_name='exposicion',
            name='nombre',
            field=models.CharField(help_text='Nombre de exposición', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(help_text='Nombre de la obra', max_length=200, unique=True, verbose_name='nombre'),
        ),
        migrations.RemoveField(
            model_name='sede',
            name='exposicion',
        ),
        migrations.AddField(
            model_name='sede',
            name='exposicion',
            field=models.ManyToManyField(to='VentaEntradas.Exposicion'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipoDeEntrada',
            field=models.OneToOneField(help_text='Tipo de entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDeEntrada', to='VentaEntradas.tipodeentrada', verbose_name='Tipo de entrada'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipoDeVisita',
            field=models.OneToOneField(help_text='Tipo de visita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDeVisita', to='VentaEntradas.tipodevisita', verbose_name='Tipo de visita'),
        ),
        migrations.DeleteModel(
            name='GestorVentaEntradas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp', to='VentaEntradas.empleado', verbose_name='empleado'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='VentaEntradas.usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalleexposicion',
            name='obra',
            field=models.OneToOneField(help_text='Obra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obr', to='VentaEntradas.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='exposicion',
            name='detalleExposicion',
            field=models.ManyToManyField(to='VentaEntradas.DetalleExposicion'),
        ),
    ]
