# Generated by Django 3.2.4 on 2021-08-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0011_auto_20210808_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='fechaInicio',
            field=models.DateField(help_text='fecha de inicio de sesión', null=True, verbose_name='fechaInicio'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='horaFin',
            field=models.TimeField(help_text='hora de fin de sesion', null=True, verbose_name='horaFin'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='horaInicio',
            field=models.TimeField(help_text='hora de inicio de sesion', null=True, verbose_name='horaInicio'),
        ),
    ]
