# Generated by Django 3.2.4 on 2021-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0012_auto_20210808_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(help_text='Apellido de empleado', max_length=200, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='calle',
            field=models.CharField(help_text='Calle', max_length=200, verbose_name='calle'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Nombre de empleado', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cantMaxPorGuia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cantMaxVisitantes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sede',
            name='horaApetura',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.TextField(max_length=200),
        ),
    ]
