# Generated by Django 3.2.4 on 2021-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaEntradas', '0018_auto_20210808_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicion',
            name='detalleExposicion',
            field=models.ManyToManyField(blank=True, null=True, to='VentaEntradas.DetalleExposicion'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='exposicion',
            field=models.ManyToManyField(blank=True, null=True, to='VentaEntradas.Exposicion'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='tarifa',
            field=models.ManyToManyField(blank=True, null=True, to='VentaEntradas.Tarifa'),
        ),
    ]
